services:
  redis:
    image: redis:latest

  hello-world:
    image: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.google111111.com/"]
      interval: 1m
      timeout: 35s
      retries: 5
      start_period: 40s

x-uffizzi:
  continuous_preview:
    delete_preview_after: 1h

x-uffizzi-ingress:
  service: hello-world
  port: 80
