services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test1

  nginx:
    image: nginx
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf

  worker:
    build:
      context: https://github.com/NealArw/example-voting-worker#main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/NealArw/example-voting-vote#main
      dockerfile: Dockerfile

  result:
    build:
      context: https://github.com/NealArw/example-voting-result#main
      dockerfile: Dockerfile
    x-uffizzi-continuous-preview:
      deploy_preview_when_pull_request_is_opened: false
      delete_preview_when_pull_request_is_closed: false
      delete_preview_after: 220h
      share_to_github: true
      deploy_preview_when_image_tag_is_created: false
      
configs:
  my_config:
    file: ./configs/vote.conf
  my_config_2:
    file: ./config2/vote2.conf


x-uffizzi-continuous-preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 120h
  share_to_github: false
  deploy_preview_when_image_tag_is_created: true

ingress:
  service: nginx
  port: 8080
