services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world:compose
      dockerfile: Dockerfile.args
      args:
        - IMAGES_PATH=images
        - TEST_ARG=Hello from compose

ingress:
  service: hello-world
  port: 80
