services:
  webhook:
    image: gcr.io/uffizzi-pro-qa-gke/webhooks-test-app:latest
    deploy:
      resources:
        limits:
          memory: 125M

ingress:
  service: webhook
  port: 80

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 1h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
