services:
  hello-world:
    build: 
      context: https://github.com/NealArw/hello-world-11#testing:test-1345
      dockerfile: test-1345/Dockerfile

ingress:
  service: hello-world
  port: 80
  
x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: test_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
