version: '3.7'

services:
  web:
    build:
      context: https://github.com/NealArw/hello-world-1#volume-from-the-root
      dockerfile: /Dockerfile
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./:

x-uffizzi:
  ingress:
    service: web
    port: 80

  continuous_preview:
    share_to_github: true
    delete_preview_after: 6h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
